[[constraint]]
  name = "github.com/goreleaser/archive"
  version = "^1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-github"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-zglob"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sync"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "github.com/apex/log"

[[constraint]]
  name = "github.com/caarlos0/ctrlc"
  version = "1.0.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/campoy/unique"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/goreleaser/nfpm"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "~2.2.6"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.47"
