baseURL = "https://goreleaser.com/"
languageCode = "en-us"
title = "GoReleaser"
copyright = "Made with ❤️ by GoReleaser contributors."
googleAnalytics = "UA-106198408-1"
theme = "hugo-apex-theme"
pygmentsCodeFences = true
pygmentsStyle = "dracula"

[params]
name = "GoReleaser"
description = "Deliver Go binaries as fast and easily as possible"
twitter = "goreleaser"
logo = "https://github.com/goreleaser.png"
ghdocsrepo = "https://github.com/goreleaser/goreleaser/edit/master/www"
