name: gosum

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/gosum.yml'
      - 'go.mod'
      - 'go.sum'

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Tidy
        run: |
          rm -f go.sum
          go mod tidy
      -
        name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): go mod tidy"
          title: "chore(deps): go mod tidy"
          body: |
            Current `go.mod` and `go.sum` don't match the source code.
          branch: go-mod-tidy
          branch-suffix: timestamp
          labels: automerge
