name: sbom-scan
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions: read-all
jobs:
  scan-sboms:
    name: scan-release-sboms
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE=$(gh release list -R goreleaser/goreleaser --exclude-pre-releases --limit 1 --json tagName | jq -r '.[0].tagName')
          echo "tag=$RELEASE" >> $GITHUB_OUTPUT
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download -R goreleaser/goreleaser "${{ steps.release.outputs.tag }}" --pattern goreleaser_Linux_x86_64.tar.gz.sbom.json
      - uses: anchore/scan-action@3c9a191a0fbab285ca6b8530b5de5a642cba332f # v7.2.2
        id: scan
        with:
          sbom: goreleaser_Linux_x86_64.tar.gz.sbom.json
          fail-build: true
          severity-cutoff: critical
      - if: always()
        uses: github/codeql-action/upload-sarif@cf1bb45a277cb3c205638b2cd5c984db1c46a412 # v4.31.7
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
